# Generated by Django 4.1.6 on 2025-04-28 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waluya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AquariumStuff',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='waluya.product')),
                ('stuff_type', models.CharField(choices=[('filter', 'Filter'), ('waterpump', 'Waterpump'), ('aerasi', 'Aerasi'), ('aksesoris', 'Aksesoris')], max_length=20)),
            ],
            bases=('waluya.product',),
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='waluya.product')),
                ('size', models.CharField(choices=[('kecil', 'Kecil'), ('sedang', 'Sedang'), ('besar', 'Besar')], max_length=10)),
                ('color', models.CharField(choices=[('gelap', 'Gelap'), ('terang', 'Terang')], max_length=10)),
            ],
            bases=('waluya.product',),
        ),
        migrations.CreateModel(
            name='FishFood',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='waluya.product')),
                ('food_type', models.CharField(choices=[('organik', 'Organik'), ('olahan', 'Olahan')], max_length=10)),
            ],
            bases=('waluya.product',),
        ),
        migrations.CreateModel(
            name='FishMedicine',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='waluya.product')),
                ('medicine_type', models.CharField(choices=[('herbal', 'Herbal'), ('kimiawi', 'Kimiawi')], max_length=10)),
            ],
            bases=('waluya.product',),
        ),
    ]
