# Generated by Django 4.1.6 on 2025-04-29 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waluya', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
