# Generated by Django 5.2 on 2025-05-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waluya', '0007_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
